apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: poker-certificate
  namespace: poker
spec:
  secretName: poker-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - poker.germainleignel.com