apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: planning-certificate
  namespace: planning
spec:
  secretName: planning-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - planning.germainleignel.com

