apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: planning-ingress
  namespace: planning
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - planning.germainleignel.com
      secretName: planning-tls
  rules:
    - host: planning.germainleignel.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: planning-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: planning-backend
                port:
                  number: 8080